events { worker_connections 1024; }
http {
  server {
    listen 80;
    server_name _;
    if ($args ~* "union|select|1=1") { return 403 "SQLi"; }
    if ($args ~* "<script|alert") { return 403 "XSS"; }
    location = /waf { root /usr/share/nginx/html; }
    location / { return 200 "WAF OK"; }
  }
}
