events { worker_connections 1024; }
http {
  limit_req_zone $binary_remote_addr zone=login:10m rate=5r/m;
  server {
    listen 80;
    server_name _;
    if ($args ~* "union|select|1=1|--|drop|insert|update|delete") { 
      access_log /var/log/nginx/blocked.log; 
      return 403 '{"blocked":"SQLi"}'; 
    }
    if ($args ~* "<script|javascript:|alert|onerror|eval") { 
      return 403 '{"blocked":"XSS"}'; 
    }
    if ($request_uri ~* "\\.\\./|proc/|etc/|winnt") { 
      return 403 '{"blocked":"LFI"}'; 
    }
    location ~* ^/(login|admin|wp-login|wp-admin|dashboard) {
      limit_req zone=login burst=10;
    }
    location = /waf {
      root /usr/share/nginx/html;
    }
    location /logs {
      alias /var/log/nginx/;
      autoindex on;
    }
    location / {
      proxy_pass http://icorkstore.kesug.com;
      proxy_set_header Host icorkstore.kesug.com;
      proxy_set_header X-Real-IP $remote_addr;
      add_header X-WAF-Protected "icorkstore-v1";
    }
  }
}
